### ISSUE TITLE
git info background blue too bright

### ISSUE THREAD

**Issue by nschloe** [riobard/bash-powerline#19]
In [the solarized theme](http://ethanschoonover.com/solarized), blue is defined as bash color 33 aka `#0087ff`, and that's how it's set in bash-powerline. However, this seems much too bright on the dark theme:

![screenshot from 2017-09-06 10-48-02](https://user-images.githubusercontent.com/181628/30103010-a92d3ae0-92f1-11e7-802a-c9714c0188d6.png)

Confusingly, [your screenshot](https://camo.githubusercontent.com/4eb103fec623fb0ffef66fd70bdf72b205086c63/68747470733a2f2f7261772e6769746875622e636f6d2f72696f626172642f626173682d706f7765726c696e652f6d61737465722f73637265656e73686f74732f736f6c6172697a65642d6461726b2d6d6f6e61636f2e706e67) shows the much more fitting and moderate `#3a8bd2`. How?

**Comment by riobard** [comment]
What terminal and color scheme are you using?

**Comment by nschloe** [comment]
gnome-terminal, solarized-dark.

**Comment by riobard** [comment]
Solarized colors do not exactly match the color scheme of your terminal. See the table at http://ethanschoonover.com/solarized

```
The Values

L*a*b values are canonical (White D65, Reference D50), other values are matched in sRGB space.

SOLARIZED HEX     16/8 TERMCOL  XTERM/HEX   L*A*B      RGB         HSB
--------- ------- ---- -------  ----------- ---------- ----------- -----------
base03    #002b36  8/4 brblack  234 #1c1c1c 15 -12 -12   0  43  54 193 100  21
base02    #073642  0/4 black    235 #262626 20 -12 -12   7  54  66 192  90  26
base01    #586e75 10/7 brgreen  240 #585858 45 -07 -07  88 110 117 194  25  46
base00    #657b83 11/7 bryellow 241 #626262 50 -07 -07 101 123 131 195  23  51
base0     #839496 12/6 brblue   244 #808080 60 -06 -03 131 148 150 186  13  59
base1     #93a1a1 14/4 brcyan   245 #8a8a8a 65 -05 -02 147 161 161 180   9  63
base2     #eee8d5  7/7 white    254 #e4e4e4 92 -00  10 238 232 213  44  11  93
base3     #fdf6e3 15/7 brwhite  230 #ffffd7 97  00  10 253 246 227  44  10  99
yellow    #b58900  3/3 yellow   136 #af8700 60  10  65 181 137   0  45 100  71
orange    #cb4b16  9/3 brred    166 #d75f00 50  50  55 203  75  22  18  89  80
red       #dc322f  1/1 red      160 #d70000 50  65  45 220  50  47   1  79  86
magenta   #d33682  5/5 magenta  125 #af005f 50  65 -05 211  54 130 331  74  83
violet    #6c71c4 13/5 brmagenta 61 #5f5faf 50  15 -45 108 113 196 237  45  77
blue      #268bd2  4/4 blue      33 #0087ff 55 -10 -45  38 139 210 205  82  82
cyan      #2aa198  6/6 cyan      37 #00afaf 60 -35 -05  42 161 152 175  74  63
green     #859900  2/2 green     64 #5f8700 60 -20  65 133 153   0  68 100  60
```

Solarized blue is _not_ #0087ff but rather #268bd2. #0087ff is the closest match if you use the terminal's default color scheme. For best result you should change your terminal's color scheme. Unfortunately Solarized does not offer a prebuilt color scheme for gnome-terminal.

**Comment by nschloe** [comment]
The palette I'm using is [gnome-terminal-colors-solarized](https://github.com/Anthony25/gnome-terminal-colors-solarized), and it looks quite accurate:

![g](https://user-images.githubusercontent.com/181628/30153541-52b28c62-93b7-11e7-987c-8e9912028568.png)

Indeed, blue is `#268bd2` here.

In the bash-powerline script, I see
```bash
readonly FG_BLUE="\[$(tput setaf 33)\]"
```
Doesn't this set blue to `#0087ff`?

**Comment by riobard** [comment]
It sets the foreground to color 33, and your terminal decides what actual color to use for color 33. What's the value of `$TERM` in your terminal?

**Comment by nschloe** [comment]
> It sets the foreground to color 33, and your terminal decides what actual color to use for color 33.

Hm, really? This seems to be the issue then, `33` produces `#0087ff` for me, tested with
```
for i in {0..255} ; do
     printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i";
     if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
         printf "\n";
     fi;
done
```

```
$ echo $TERM
xterm-256color
```

**Comment by riobard** [comment]
It's indeed very strange. Solarized used color 33 as blue for 256-color terminals, and it should produce sRGB(38, 139, 210) if your terminal is properly configured. Maybe you should try a different terminal emulator and see if this is a bug in gnome-terminal.

**Comment by nschloe** [comment]
Alright, I'll dig more in this direction. Thanks for the help! Will reopen in case I find a bug in bash-powerline.
