### ISSUE TITLE
Would you please use the following code

### ISSUE THREAD

**Issue by liaoya** [riobard/bash-powerline#28]
I like bash-powerline very much. I think the following code is much portable

`readonly SYMBOL_GIT_BRANCH=$(echo -e '\ue0a0')`

I use Linux and Windows. I think the branch glyphs can not display on my environment.

**Comment by nmajin** [comment]
Why don't you submit a pull request for whatever you are trying to inject into the code base?

**Comment by riobard** [comment]
Fixed by #30
